#include "stdafx.h"
#include "Writer.h"

bool Writer::openOutputFile (char *output) {
  if (strcmp (&output[strlen (output) - 4], ".csv") != 0) {
    return false; // check whether it's a .c file 
  } else if ((outfile = fopen (output, "r")) == NULL) {
    return false;
  } else {
    return true;
  }
}


Writer::Writer (char *output) {
  if (openOutputFile (output)) { //open the output file succeed
    symbolList.clear ();
  } else {
    // Report an error to ErrorNotifier
    delete this;
  }
}


Writer::~Writer () {
  fclose (outfile);
}

void Writer::addItem (PID newID) {
  symbolList.push_back(newID);
}

void Writer::writeFile () {
  fprintf (outfile, "%s%s", "**This file is generated by Lexer**,,,,\n", "Token,Value,Line,Offset,\n");
  for each (PID p in symbolList) {
    fprintf (outfile, "%3d,", p->token);
    fprintf (outfile, "%s", p->unionValue.strValue);//TO-DO: Determine the type by token -> to use numValue/ stringValue
    fprintf (outfile, "%d,%d,\n", p->lineNum, p->lineOffset);
  }
}

